webserverConfig:
  bindHost: 0.0.0.0
  port: 8060
mqttConfig:
  serverUrl: 'mqtt://localhost'
  serverUsername: harmony
  serverPassword: harmony
  enabled: true
websocketConfig:
  serverUrl: 'ws://192.168.1.135:1234'
  enabled: true
buttons:
  - id: 0
    name: Home
    action: WEBSOCKET
    websocketMessage: '"GetVersion"'
    enabled: true
  - id: 1
    name: Rev
    action: WEBSOCKET
    websocketMessage: '{"SetMute":"toggle"}'
    enabled: true
  - id: 2
    name: Fwd
    action: WEBSOCKET
    websocketMessage: '{"SetMute":"toggle"}'
    enabled: true
  - id: 3
    name: Play
    action: GET
    url: 'https://www.example.com'
    httpHeaders: {}
    enabled: false
  - id: 4
    name: Select
    action: GET
    url: 'https://www.example.com'
    httpHeaders: {}
    enabled: false
  - id: 5
    name: Left
    action: GET
    url: 'https://www.example.com'
    httpHeaders: {}
    enabled: false
  - id: 6
    name: Right
    action: GET
    url: 'https://www.example.com'
    httpHeaders: {}
    enabled: false
  - id: 7
    name: Down
    action: WEBSOCKET
    websocketMessage: '{"SetVolume": {"changeBy": -3, "max": 30, "min":-35}}'
    enabled: true
  - id: 8
    name: Up
    action: WEBSOCKET
    websocketMessage: '{"SetVolume": {"changeBy": 3, "max": 30, "min":-35}}'
    enabled: true
  - id: 9
    name: Back
    action: GET
    url: 'https://www.example.com'
    httpHeaders: {}
    enabled: false
  - id: 10
    name: InstantReplay
    action: GET
    url: 'https://www.example.com'
    httpHeaders: {}
    enabled: false
  - id: 11
    name: Info
    action: WEBSOCKET
    websocketMessage: '"GetVolume"'
    enabled: true
  - id: 12
    name: Backspace
    action: GET
    url: 'https://www.example.com'
    httpHeaders: {}
    enabled: false
  - id: 13
    name: Search
    action: GET
    url: 'https://www.example.com'
    httpHeaders: {}
    enabled: false
  - id: 14
    name: Enter
    action: GET
    url: 'https://www.example.com'
    httpHeaders: {}
    enabled: false
